const dotenv = require("dotenv").config();

const PORTS = process.env.PORT;
const MONGODB_CONNECTION_STRING = process.env.MONGO_DB_CONNECTION_STRING;
const ACESS_TOKKEN_SECRET_KEY = process.env.ACESS_TOKKEN_SECRET_KEY;
const REFRESH_TOKKEN_SECRET_KEY = process.env.REFRESH_TOKKEN_SECRET_KEY;
const BACKEND_SERVER_PATH = process.env.BACKEND_SERVER_PATH;
module.exports = {
    PORTS,
    REFRESH_TOKKEN_SECRET_KEY, ACESS_TOKKEN_SECRET_KEY,
    MONGODB_CONNECTION_STRING,
    BACKEND_SERVER_PATH
}
